name: sbemoored
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - pandas
  - scipy
  - xarray
  - netcdf4
  - gsw
  - pip
  - pip:
    - xmltodict
    - "-e /Users/gunnar/Projects/python/gvpy"
    # - "-e git+https://github.com/gunnarvoet/gvpy#egg=gvpy"
    - "-e ."
